apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    # Memory metrics for scaling
    #
    # The beta version API version includes support for scaling on memory and custom metrics.
    # The new fields introduced in autoscaling/v2beta2 are preserved as annotations when working with autoscaling/v1.
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"memory", "targetAverageUtilization":80}}]'
  labels:
    app: noobaa
  name: noobaa-endpoint
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: noobaa-endpoint
  targetCPUUtilizationPercentage: 80
